CREATE database BIG_BREAD;
use BIG_BREAD;
CREATE table BIG_BREAD_
 (FECHA date, PRODUCTOS varchar(10), INSUMOS varchar(10), PRODUCCION_DIARIA varchar(10), RECETAS varchar(10));
CREATE table PRODUCTOS
(ID_PRODUCTO varchar(10),DETALLE_PRODUCTO varchar(20),COSTO_INDIVIDUAL varchar(10), VALOR_VENTA_AL_PÚBLICO float(5), 
STOCK float(5));
CREATE table INSUMOS
(INSUMO varchar(10), ID_INSUMO varchar(10),COSTO float(10), STOCK_INSUMOS float(5) );
CREATE table RECETA
(ID_PROCESO varchar(10), PRODUCTO varchar(10), ID_PRODUCTO varchar(10), INSUMO varchar(10), ID_INSUMO varchar(10), CANTIDAD_INSUMO int(10), DESCRIPCION_DEL_PROCESO varchar(5000));
CREATE table PRODUCCION_DIARIA
(FECHA date, ID_PROCESO varchar(10), ID_PRODUCTO varchar(10),CANTIDAD_PRODUCIDA varchar(10));