-- MySQL Script generated by MySQL Workbench
-- Sun May 21 20:20:00 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Big_Bread
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Big_Bread` ;

-- -----------------------------------------------------
-- Schema Big_Bread
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Big_Bread` DEFAULT CHARACTER SET utf8 ;
USE `Big_Bread` ;

-- -----------------------------------------------------
-- Table `Big_Bread`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Big_Bread`.`Productos` (
  `idProductos` INT NOT NULL AUTO_INCREMENT,
  `Pan francés` VARCHAR(45) NULL,
  `Facturas` VARCHAR(45) NULL,
  `Criollitos` VARCHAR(45) NULL,
  PRIMARY KEY (`idProductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Big_Bread`.`Insumos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Big_Bread`.`Insumos` (
  `idInsumos` INT NOT NULL AUTO_INCREMENT,
  `idProductos` INT NOT NULL,
  `Harina` VARCHAR(45) NULL,
  `Azúcar` VARCHAR(45) NULL,
  `Agua` VARCHAR(45) NULL,
  `Manteca` VARCHAR(45) NULL,
  `Levadura` VARCHAR(45) NULL,
  `Leche` VARCHAR(45) NULL,
  `Sal` VARCHAR(45) NULL,
  PRIMARY KEY (`idInsumos`),
  CONSTRAINT `IdProductos`
    FOREIGN KEY ()
    REFERENCES `Big_Bread`.`Productos` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Big_Bread`.`Producción_diaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Big_Bread`.`Producción_diaria` (
  `idProducción_diaria` INT NOT NULL AUTO_INCREMENT,
  `IdProductos` INT NOT NULL,
  `IdInsumos` INT NOT NULL,
  PRIMARY KEY (`idProducción_diaria`),
  CONSTRAINT `IdProductos`
    FOREIGN KEY ()
    REFERENCES `Big_Bread`.`Productos` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `IdInsumos`
    FOREIGN KEY ()
    REFERENCES `Big_Bread`.`Insumos` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Big_Bread`.`Recetas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Big_Bread`.`Recetas` (
  `idRecetas` INT NOT NULL,
  `idProductos` INT NOT NULL,
  `idInsumos` INT NOT NULL,
  PRIMARY KEY (`idRecetas`),
  CONSTRAINT `idProductos`
    FOREIGN KEY ()
    REFERENCES `Big_Bread`.`Productos` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idInsumos`
    FOREIGN KEY ()
    REFERENCES `Big_Bread`.`Insumos` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
